/**
 * @file src/services/mock/mockAssistantApi.js
 * High-fidelity Mock API simulating future FastAPI + RAG backend responses.
 * 
 * - Includes latency simulation
 * - Stores state in memory with localStorage persistence
 * - Returns structured Message, Source, and Conversation objects
 * - Uses clearly labeled demo/fictional sources
 */

import { DOCUMENT_TYPES, ROLES, createConversation, createMessage } from '../../types/assistant'

const STORAGE_KEY_CONVERSATIONS = 'bis_assistant_mock_conversations'
const STORAGE_KEY_MESSAGES = 'bis_assistant_mock_messages'

// Demo Sources Library
const DEMO_SOURCES = {
  CEILING_FAN: [
    {
      id: 'src_is374_demo',
      title: 'Electric Ceiling Type Fans and Regulators Specification',
      document_type: DOCUMENT_TYPES.STANDARD,
      document_id: 'IS 374:2019 (Demo)',
      page: 12,
      clause: 'Clause 4.2 & Clause 8.1',
      snippet:
        'Clause 4.2 specifies electrical insulation resistance (minimum 2 MΩ at 500V DC). Clause 8.1 requires service value measurement for air delivery under rated voltage and frequency.',
      url: 'https://example.bis.gov.in/standards/demo/IS374-2019',
    },
    {
      id: 'src_scheme1_fan_demo',
      title: 'Product Specific Guidelines for Ceiling Fans under Scheme-I',
      document_type: DOCUMENT_TYPES.GUIDELINE,
      document_id: 'BIS-STI/374/1 (Demo)',
      page: 4,
      clause: 'Scheme of Inspection and Testing (SIT)',
      snippet:
        'Factory must maintain in-house testing equipment for routine electrical safety checks, high-voltage flash test (1500V AC for 1 second), and air delivery chamber calibration.',
      url: 'https://example.bis.gov.in/guidelines/demo/SIT-374',
    },
  ],
  STEEL_BOTTLE: [
    {
      id: 'src_is17803_demo',
      title: 'Stainless Steel Vacuum Flasks and Insulated Bottles Specification',
      document_type: DOCUMENT_TYPES.STANDARD,
      document_id: 'IS 17803:2022 (Demo)',
      page: 7,
      clause: 'Clause 5.1 & Clause 6.4',
      snippet:
        'All food contact surfaces shall be manufactured using food-grade stainless steel conforming to grade 304 or 316. Thermal retention test requires liquid temperature to remain above 60°C after 6 hours.',
      url: 'https://example.bis.gov.in/standards/demo/IS17803-2022',
    },
    {
      id: 'src_qco_steel_demo',
      title: 'Quality Control Order for Stainless Steel Water Bottles',
      document_type: DOCUMENT_TYPES.QCO,
      document_id: 'DPIIT-QCO-2023/SB (Demo)',
      page: 2,
      clause: 'Section 3 - Compulsory BIS Certification',
      snippet:
        'No person shall manufacture, import, distribute, or sell stainless steel bottles without bearing the Standard Mark (ISI Mark) issued under BIS Scheme-I.',
      url: 'https://example.bis.gov.in/qco/demo/steel-bottles-2023',
    },
  ],
  GENERAL_SCHEME1: [
    {
      id: 'src_scheme1_manual_demo',
      title: 'BIS Product Certification Scheme-I (ISI Mark) Operating Manual',
      document_type: DOCUMENT_TYPES.SCHEME,
      document_id: 'BIS-MAN-SCH1-V4 (Demo)',
      page: 18,
      clause: 'Chapter 3: Documentation & Factory Inspection',
      snippet:
        'Applicants must submit: Form-I, Factory layout, List of manufacturing machinery, Calibration certificates for in-house testing equipment, and Appointment of qualified Quality Control personnel.',
      url: 'https://example.bis.gov.in/schemes/demo/scheme-1-manual',
    },
    {
      id: 'src_lab_manual_demo',
      title: 'General Requirements for Competence of Testing Laboratories',
      document_type: DOCUMENT_TYPES.LAB_MANUAL,
      document_id: 'IS/ISO 17025 (Demo Guidelines)',
      page: 31,
      clause: 'Clause 6.2 & Clause 7.8',
      snippet:
        'Sample collection by BIS inspecting officer must follow random sampling procedure. Third-party testing reports must be generated by NABL accredited or BIS recognized laboratories.',
      url: 'https://example.bis.gov.in/labs/demo/iso17025',
    },
  ],
}

// Initial Seed Conversations
const INITIAL_CONVERSATIONS = [
  {
    id: 'conv_today_1',
    title: 'Electric ceiling fan certification',
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    message_count: 2,
    last_message: 'For an electric ceiling fan, the mandatory standard is IS 374:2019...',
  },
  {
    id: 'conv_today_2',
    title: 'Steel bottle standard compliance',
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    message_count: 2,
    last_message: 'Stainless steel water bottles fall under IS 17803:2022...',
  },
  {
    id: 'conv_yesterday_1',
    title: 'BIS certification requirements',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 25).toISOString(),
    message_count: 2,
    last_message: 'To obtain a BIS Scheme-I (ISI Mark) license, you need...',
  },
]

// Initial Seed Messages
const INITIAL_MESSAGES = {
  conv_today_1: [
    {
      id: 'msg_fan_u1',
      conversation_id: 'conv_today_1',
      role: ROLES.USER,
      content: 'What is required to certify an electric ceiling fan under BIS?',
      created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      sources: [],
    },
    {
      id: 'msg_fan_a1',
      conversation_id: 'conv_today_1',
      role: ROLES.ASSISTANT,
      content: `### BIS Certification Requirements for Electric Ceiling Fans

Electric ceiling fans are covered under mandatory BIS certification under the **Quality Control Order (QCO)**.

#### 1. Applicable Standard
* **Primary Standard:** **IS 374:2019 (Demo)** — *Electric Ceiling Type Fans and Regulators*
* **Scope:** Covers domestic and commercial ceiling fans, single-phase AC powered.

#### 2. Key Technical Requirements
* **Air Delivery & Service Value:** Air delivery must meet energy efficiency thresholds measured in cubic meters per minute ($m^3/min$).
* **Electrical Safety:** Insulation resistance must not be less than $2\\text{ M}\\Omega$ (tested at 500V DC).
* **High Voltage Flash Test:** Withstand 1500V AC for 1 second between live parts and body.
* **Blade Balance & Wobble:** Maximum allowable dynamic runout is strictly monitored under Section 6.

#### 3. Mandatory Steps for Industry
1. **In-house Test Lab Setup:** Install high-voltage flash tester, air delivery chamber, and power analyzer.
2. **Online Application:** Submit Form-I on the **Manakonline Portal** under Scheme-I (ISI Mark).
3. **Factory Audit & Sample Testing:** BIS inspecting officers draw production samples for independent laboratory testing at a recognized BIS laboratory.

> **Next Steps:** Ensure your testing equipment calibration certificates are valid within the last 12 months before scheduling the factory audit.`,
      created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      sources: DEMO_SOURCES.CEILING_FAN,
    },
  ],
  conv_today_2: [
    {
      id: 'msg_steel_u1',
      conversation_id: 'conv_today_2',
      role: ROLES.USER,
      content: 'Do stainless steel water bottles require mandatory ISI mark?',
      created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
      sources: [],
    },
    {
      id: 'msg_steel_a1',
      conversation_id: 'conv_today_2',
      role: ROLES.ASSISTANT,
      content: `### Mandatory Certification for Stainless Steel Bottles

**Yes.** Under the latest DPIIT Quality Control Order, all stainless steel water bottles and vacuum flasks must mandatorily carry the **ISI Mark**.

#### Key Regulatory Highlights:
* **Standard:** **IS 17803:2022 (Demo)** — *Stainless Steel Vacuum Flasks and Insulated Containers*
* **Material Grade:** Inner liner must use food-grade austenitic stainless steel (Grade 304 or 316).
* **Thermal Insulation:** Hot liquids must maintain $\\ge 60^\\circ\\text{C}$ after 6 hours of static storage at room temperature.
* **Leakage Test:** Cap assembly tested under inverted pressure of 0.5 bar without liquid seepage.

#### Consequences of Non-Compliance:
Manufacturing, importing, or selling without the ISI mark is prohibited under the BIS Act, 2016.`,
      created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
      sources: DEMO_SOURCES.STEEL_BOTTLE,
    },
  ],
  conv_yesterday_1: [
    {
      id: 'msg_sch1_u1',
      conversation_id: 'conv_yesterday_1',
      role: ROLES.USER,
      content: 'What documents are required to apply for BIS Scheme-I license?',
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
      sources: [],
    },
    {
      id: 'msg_sch1_a1',
      conversation_id: 'conv_yesterday_1',
      role: ROLES.ASSISTANT,
      content: `### Documentation Checklist for BIS Scheme-I (ISI Mark)

To apply for a product certification license under Scheme-I, prepare the following documents:

| Category | Required Document | Remarks |
| :--- | :--- | :--- |
| **Legal Identity** | Certificate of Incorporation / GST Registration / MSME Udyam | Must clearly show factory address |
| **Factory Premises** | Factory License / Land Ownership / Lease Agreement | Minimum 3 years validity |
| **Manufacturing** | Complete Machinery List with capacities & serial numbers | In-house manufacturing setup |
| **Quality Control** | In-house Test Equipment & Valid Calibration Certificates | Traceable to NPL / NABL |
| **Personnel** | Degree/Diploma certificates of Quality Control Personnel | At least 1 qualified QC in-charge |
| **Manufacturing Process**| Flow chart indicating inspection & test hold points | From raw material to packaging |

#### Application Process
1. Register on **Manakonline**.
2. Submit online application with initial audit fees.
3. BIS factory audit and sample drawing.
4. License grant upon satisfactory laboratory test results.`,
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 25).toISOString(),
      sources: DEMO_SOURCES.GENERAL_SCHEME1,
    },
  ],
}

// In-Memory Storage Cache with localStorage sync
class MockStorage {
  constructor() {
    this.conversations = this.loadConversations()
    this.messages = this.loadMessages()
  }

  loadConversations() {
    try {
      const data = localStorage.getItem(STORAGE_KEY_CONVERSATIONS)
      if (data) return JSON.parse(data)
    } catch {
      // LocalStorage not available or parse error
    }
    return [...INITIAL_CONVERSATIONS]
  }

  loadMessages() {
    try {
      const data = localStorage.getItem(STORAGE_KEY_MESSAGES)
      if (data) return JSON.parse(data)
    } catch {
      // LocalStorage not available or parse error
    }
    return { ...INITIAL_MESSAGES }
  }

  save() {
    try {
      localStorage.setItem(STORAGE_KEY_CONVERSATIONS, JSON.stringify(this.conversations))
      localStorage.setItem(STORAGE_KEY_MESSAGES, JSON.stringify(this.messages))
    } catch {
      // Ignore storage errors
    }
  }
}

const mockStore = new MockStorage()

// Helper: simulate network delay
const delay = (ms = 700) => new Promise((resolve) => setTimeout(resolve, ms))

/**
 * Intelligent Mock Response Generator based on query keywords
 * @param {string} prompt
 * @param {string} conversationId
 * @returns {{ content: string, sources: Array }}
 */
function generateMockResponse(prompt, conversationId) {
  const query = prompt.toLowerCase().trim()

  if (query.includes('fan') || query.includes('is 374') || query.includes('motor')) {
    return {
      content: `### Technical Guidance: Electric Fans (IS 374:2019 Demo)

Based on the official **IS 374:2019 (Demo)** standard for ceiling fans:

1. **Safety Testing Requirements:**
   * **Earth Continuity:** Ground resistance $\\le 0.1\\,\\Omega$.
   * **High Voltage Flash Test:** Tested at 1.5 kV AC for 1 second with no breakdown.
   * **Temperature Rise:** Winding temperature rise must not exceed $75^\\circ\\text{C}$ under full load.

2. **Performance Metrics:**
   * Air delivery measurement in a standardized chamber conforming to Clause 8.1.
   * Service value threshold must be met according to Star Rating criteria.

3. **Required In-House Equipment:**
   * Digital power analyzer, anemometer rig, HV flash tester, winding resistance bridge, and dynamic balancing rig.`,
      sources: DEMO_SOURCES.CEILING_FAN,
    }
  }

  if (query.includes('bottle') || query.includes('flask') || query.includes('steel') || query.includes('is 17803')) {
    return {
      content: `### Guidance on Stainless Steel Bottles (IS 17803:2022 Demo)

Under **IS 17803:2022 (Demo)** and the relevant Quality Control Order:

* **Material Composition:** Food-contact stainless steel parts must conform to Grade 304 or 316.
* **Drop Impact Test:** Flask dropped from 1.2m height onto concrete floor without leakage or shell rupture.
* **Thermal Retention:** Maintains heat retention above $60^\\circ\\text{C}$ over a 6-hour test cycle.
* **Marking:** Must display Manufacturer Name/Brand, Standard Number (IS 17803), and the 7-digit License (CM/L) number under the ISI mark.`,
      sources: DEMO_SOURCES.STEEL_BOTTLE,
    }
  }

  if (query.includes('document') || query.includes('paper') || query.includes('apply') || query.includes('form')) {
    return {
      content: `### Required Application Documents for BIS License

To submit a complete application under **BIS Scheme-I (ISI Mark)**:

1. **Business Proof:** Registration Certificate (CIN/GST/MSME).
2. **Plant & Machinery:** Machinery details along with installed capacity and calibration status.
3. **Quality Control Staff:** Appointment letter, educational qualification proof of QC supervisors.
4. **Test & Inspection Scheme (SIT):** Acceptance of the prescribed Scheme of Inspection and Testing.
5. **Raw Material Test Certificates:** Mill test certificates for incoming steel, plastics, or electrical components.

> **Tip:** You can upload all files directly via the **Documents** section in this portal for preliminary automated verification.`,
      sources: DEMO_SOURCES.GENERAL_SCHEME1,
    }
  }

  if (query.includes('lab') || query.includes('test') || query.includes('nabl') || query.includes('testing')) {
    return {
      content: `### BIS Testing & Laboratory Protocols

Testing procedures follow **IS/ISO 17025 (Demo Guidelines)**:

* **In-House Testing:** Daily batch testing must be recorded in the official Factory Quality Register according to the SIT document.
* **Independent Verification:** BIS officers select random samples during factory audit. These samples are sealed and sent to a BIS recognized laboratory.
* **Sample Retesting:** In case of marginal non-conformance, a counter-sample may be retested according to Clause 7.8 guidelines.`,
      sources: [DEMO_SOURCES.GENERAL_SCHEME1[1]],
    }
  }

  if (query.includes('simple') || query.includes('explain') || query.includes('what is bis')) {
    return {
      content: `### BIS Certification Explained in Simple Language

**Bureau of Indian Standards (BIS)** is the National Standards Body of India responsible for the harmonious development of standardisation, marking, and quality certification of goods.

#### How It Works for Manufacturers:
1. **Standard:** BIS publishes a specific Indian Standard (IS code) detailing how a product must be built.
2. **Compliance:** You manufacture the product meeting those standard specifications and test it in-house.
3. **License:** BIS inspects your factory and issues a **Standard Mark (ISI Mark)** license.
4. **Trust:** Consumers and government procurement recognize the ISI Mark as proof of quality and safety.`,
      sources: DEMO_SOURCES.GENERAL_SCHEME1,
    }
  }

  // General fallback response
  return {
    content: `### BIS Technical Advisory

Thank you for your query regarding **${prompt}**.

Based on the standard BIS regulatory framework and published guidelines:

* **Verification of Applicable Code:** Please confirm your product category to map against the exact Indian Standard (IS code).
* **Scheme Selection:** Most industrial and consumer products fall under **Scheme-I (Domestic Product Certification)** or **CRS (Compulsory Registration Scheme)** for electronics.
* **Testing & Quality Assurance:** Manufacturers must ensure batch-wise quality testing as outlined in the designated Scheme of Testing and Inspection (STI).

Feel free to specify your product type or standard code for in-depth technical requirements.`,
    sources: DEMO_SOURCES.GENERAL_SCHEME1,
  }
}

/**
 * Mock Assistant API Service
 */
export const mockAssistantApi = {
  /**
   * Fetch all conversations
   * @returns {Promise<{ conversations: Array }>}
   */
  async getConversations() {
    await delay(350)
    return {
      conversations: [...mockStore.conversations].sort(
        (a, b) => new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime()
      ),
    }
  },

  /**
   * Fetch a single conversation with its messages
   * @param {string} conversationId
   * @returns {Promise<{ conversation: Object, messages: Array }>}
   */
  async getConversation(conversationId) {
    await delay(300)
    const conversation = mockStore.conversations.find((c) => c.id === conversationId)
    if (!conversation) {
      throw new Error(`Conversation ${conversationId} not found`)
    }
    const messages = mockStore.messages[conversationId] || []
    return {
      conversation,
      messages: [...messages],
    }
  },

  /**
   * Create a new conversation
   * @param {string} [title='New Conversation']
   * @returns {Promise<{ conversation: Object }>}
   */
  async createConversation(title = 'New Conversation') {
    await delay(300)
    const newConv = createConversation({ title })
    mockStore.conversations.unshift(newConv)
    mockStore.messages[newConv.id] = []
    mockStore.save()
    return { conversation: newConv }
  },

  /**
   * Delete a conversation
   * @param {string} conversationId
   * @returns {Promise<{ success: boolean, id: string }>}
   */
  async deleteConversation(conversationId) {
    await delay(300)
    mockStore.conversations = mockStore.conversations.filter((c) => c.id !== conversationId)
    delete mockStore.messages[conversationId]
    mockStore.save()
    return { success: true, id: conversationId }
  },

  /**
   * Send a message and receive assistant answer with sources
   * @param {Object} params
   * @param {string} params.conversationId
   * @param {string} params.message
   * @returns {Promise<{ message: Object, conversation: Object }>}
   */
  async sendMessage({ conversationId, message }) {
    await delay(800) // Realistic RAG + LLM inference latency simulation

    if (!message || !message.trim()) {
      throw new Error('Message content cannot be empty.')
    }

    // Ensure conversation exists or create one
    let conversation = mockStore.conversations.find((c) => c.id === conversationId)
    if (!conversation) {
      const generatedTitle = message.length > 32 ? `${message.substring(0, 32)}...` : message
      conversation = createConversation({ id: conversationId, title: generatedTitle })
      mockStore.conversations.unshift(conversation)
      mockStore.messages[conversationId] = []
    }

    // Create user message
    const userMsg = createMessage({
      conversationId,
      role: ROLES.USER,
      content: message,
    })

    if (!mockStore.messages[conversationId]) {
      mockStore.messages[conversationId] = []
    }
    mockStore.messages[conversationId].push(userMsg)

    // Generate AI answer & sources
    const { content, sources } = generateMockResponse(message, conversationId)
    const assistantMsg = createMessage({
      conversationId,
      role: ROLES.ASSISTANT,
      content,
      sources,
    })

    mockStore.messages[conversationId].push(assistantMsg)

    // Update conversation metadata
    conversation.updated_at = new Date().toISOString()
    conversation.message_count = mockStore.messages[conversationId].length
    conversation.last_message = message.substring(0, 60)
    if (conversation.title === 'New Conversation' || conversation.title === '') {
      conversation.title = message.length > 35 ? `${message.substring(0, 35)}...` : message
    }

    mockStore.save()

    return {
      message: assistantMsg,
      conversation,
    }
  },

  /**
   * Regenerate the last assistant response or a specific message
   * @param {Object} params
   * @param {string} params.conversationId
   * @param {string} params.messageId
   * @returns {Promise<{ message: Object }>}
   */
  async regenerateMessage({ conversationId, messageId }) {
    await delay(750)
    const messages = mockStore.messages[conversationId] || []
    const targetIndex = messages.findIndex((m) => m.id === messageId)

    if (targetIndex === -1) {
      throw new Error('Message not found for regeneration.')
    }

    // Find the preceding user prompt
    let previousUserPrompt = 'BIS standards guidance'
    for (let i = targetIndex - 1; i >= 0; i--) {
      if (messages[i].role === ROLES.USER) {
        previousUserPrompt = messages[i].content
        break
      }
    }

    const { content, sources } = generateMockResponse(previousUserPrompt, conversationId)

    const updatedMessage = {
      ...messages[targetIndex],
      content: `${content}\n\n*(Regenerated response)*`,
      sources,
      created_at: new Date().toISOString(),
    }

    messages[targetIndex] = updatedMessage
    mockStore.save()

    return { message: updatedMessage }
  },

  /**
   * Clear all messages in a conversation
   * @param {string} conversationId
   * @returns {Promise<{ success: boolean }>}
   */
  async clearConversation(conversationId) {
    await delay(250)
    mockStore.messages[conversationId] = []
    const conv = mockStore.conversations.find((c) => c.id === conversationId)
    if (conv) {
      conv.message_count = 0
      conv.last_message = ''
      conv.updated_at = new Date().toISOString()
    }
    mockStore.save()
    return { success: true }
  },
}
